version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./ui/
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend/
    ports:
      - 80:80